# What is Numpy?
    

 Python Library for creating N-dimensional Arrays
 Ability to quickly broadcast functions
 Built-in linear algebra, statiscal distributions, trigonometric, and random number capabilities.

## Why use NumPy?
While Numpy structures look similar to standard Python Lists, they are much more efficient.


##Creating Arrays with Numpy

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
mylist

[1, 2, 3]

In [5]:
myarr = np.array(mylist)

In [6]:
type(myarr)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
len(np.linspace(3,7,3))

3

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.random.rand(5,2)

array([[0.74070575, 0.6085989 ],
       [0.57593455, 0.10161776],
       [0.48186865, 0.1265276 ],
       [0.40083492, 0.55919609],
       [0.09533035, 0.98281039]])

In [25]:
np.random.randn(10)

array([-1.92298992, -0.18613191, -0.8447424 , -0.15356604, -0.33418911,
       -0.15748199,  0.44396946,  0.3124088 , -0.43382088,  0.81290781])

In [27]:
np.random.randn(2,3)

array([[-0.125887  , -0.84585618, -0.50406709],
       [ 1.41295563, -1.67834738,  1.06407354]])

In [28]:
np.random.randint(5,101,(5,2))

array([[35, 51],
       [21, 16],
       [50, 72],
       [50, 54],
       [40, 70]])

In [29]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr = np.arange(0,25)

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr = np.random.randint(0,101,10)

In [33]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [34]:
ranarr.max()

99

In [35]:
ranarr.min()

2

In [37]:
ranarr.argmax()

5

In [38]:
ranarr.argmin()

7

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)