# Dimension

In [1]:
import numpy as np

In [2]:
arr = np.array([12,3,4,5])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
a=np.array(12)

In [5]:
print(a.ndim)

0


In [6]:
a=np.array([1,2,3])
print(a.ndim)

1


In [9]:
a=np.array([[1,2,3],[1,2,3]])
print(a.ndim)

2


In [10]:
arr=np.array([2,3,4,5],ndmin=5)
print(arr)

[[[[[2 3 4 5]]]]]


# Shape


In [11]:
c=np.array([[1,2,3],[2,3,4]])

In [12]:
print(c.shape)

(2, 3)


In [13]:
c.shape = (2,2)
#cannot reshape

ValueError: cannot reshape array of size 6 into shape (2,2)

In [18]:
a=np.array([[1,2,3],[4,5,6],[1,2,3],[1,2,3]])
b = a.reshape(2,3,2)
print(b)

[[[1 2]
  [3 4]
  [5 6]]

 [[1 2]
  [3 1]
  [2 3]]]


# Size


In [19]:
arr=np.array([1,2,3,4,5]) 
print(arr.dtype)

int32


In [20]:
arr.itemsize

4

In [23]:
arr=np.array([1,2,3,4,5],dtype = 'int16') 
arr.itemsize

2

# Index and Slicing

In [24]:
arr=np.array([1,2,3,4,5])
print(arr[1])

2


In [25]:
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [27]:
print(arr[1,2])

3


# Iter


In [29]:
arr=np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [30]:
arr = np.array([[2,3,4],[2,3,6]])

In [31]:
arr

array([[2, 3, 4],
       [2, 3, 6]])

In [32]:
for x in arr:
    print(x)

[2 3 4]
[2 3 6]


In [33]:
for x in arr:
    for y in arr:
        print(y)

[2 3 4]
[2 3 6]
[2 3 4]
[2 3 6]


In [34]:
for x in np.nditer(arr):
    print(x)

2
3
4
2
3
6


In [35]:
for idx, x, in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 2
(0, 1) 3
(0, 2) 4
(1, 0) 2
(1, 1) 3
(1, 2) 6


In [36]:
arr2 = np.arange(5)

In [37]:
arr2

array([0, 1, 2, 3, 4])

In [40]:
arr3 = np.linspace(10,20,5)
arr3

array([10. , 12.5, 15. , 17.5, 20. ])

In [42]:
arr3 = np.linspace(10,20,5, endpoint = False)
arr3

array([10., 12., 14., 16., 18.])

In [45]:
arr3 = np.logspace(1.0,2.0, num=10)
arr3

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

# Zeroes

In [46]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [49]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [50]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.full((2,2),99, dtype='int32')

array([[99, 99],
       [99, 99]])

In [53]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.empty([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
np.all([[True, False],[True,False]])

False

In [59]:
np.any([[True,False],[True,False]])

True